from .cat import Cat
from .dog import Dog
from .duck import Duck
from .flamingo import Flamingo
from .frog import Frog
from .goldfish import Goldfish
from .goose import Goose
from .groundhog import Groundhog
from .horse import Horse
from .lizard import Lizard
from .loon import Loon
from .snake import Snake
from .spider import Spider
from .squirrel import Squirrel
from .toad import Toad
