from .animals import Horse
from .animals import Toad
from .animals import Dog
from .animals import Cat
from .animals import Groundhog
from .animals import Snake
from .animals import Spider
from .animals import Squirrel
from .animals import Frog
from .animals import Lizard
from .animals import Goldfish
from .animals import Loon
from .animals import Goose
from .animals import Flamingo
from .animals import Duck
